In [22]:
import requests
import pandas as pd 
from tqdm import tqdm
import time

api_code = pd.read_csv('D:\\coding\\선거인명부 조사\\nec_urls_1일차.csv')
# elections = ['20250603','20240410','20220601','20220309','20200415','20180613','20180509','20160413']
elections = ['20170509']

df = pd.DataFrame()

for election in elections:
    for row in tqdm(api_code.itertuples(), total=len(api_code), desc=f"{election} 선거"):
        url = 'http://apis.data.go.kr/9760000/ElcntInfoInqireService/getVtdsElcntInfoInqire'
        params ={'serviceKey' : 'iekz5HrDyh68jtoJkTI7uIBd9lDLt+oeBobNL2Iny9dzUVX7+MWHZqsMIJtyiwjSxQqvzSz5FAtjplZKCk1+zA==', 
                'pageNo' : '1', 
                'numOfRows' : '100', 
                'resultType' : 'json', 
                'sgId' : election, 
                'sdName' : row.cityName, 
                'wiwName' : row.townName}
        
        response = requests.get(url, params=params)

        try:
            data = pd.json_normalize(response.json()['response']['body']['items']['item'])
            df = pd.concat([df, data], axis=0)
        except:
            pass

        time.sleep(2)

df.to_csv('2017대선_선거인명부.csv', index=False)

20170509 선거: 100%|██████████| 253/253 [12:03<00:00,  2.86s/it]

In [ ]:
import duckdb
import pandas as pd 



df = df.astype({'cfmtnElcnt':'int','ppltCnt':'int'}) 
#cfmtnElcnt: 확정선거인수, ppltCnt:인구수

result = duckdb.query(
    '''
SELECT * 
FROM df 
WHERE tpgName != '합계' 
  AND cfmtnElcnt > ppltCnt;
    '''
).df() # tpgName: 투표구명
result

Empty DataFrame
Columns: [num, sgId, sdName, wiwName, emdName, tpgName, ppltCnt, ntabPpltCnt, frgnrPpltCnt, cfmtnElcnt, cfmtnRacnt, cfmtnFrgnrCnt, cfmtnManElcnt, cfmtnManRacnt, cfmtnManFrgnrCnt, cfmtnFmlElcnt, cfmtnFmlRacnt, cfmtnFmlFrgnrCnt, cfmtnRdvtDccnt, cfmtnNtabRdvtDccnt, cfmtnRdvtManDccnt, cfmtnNtabRdvtManDccnt, cfmtnRdvtFmlDccnt, cfmtnNtabRdvtFmlDccnt]
Index: []

[0 rows x 24 columns]

In [23]:
df1 = pd.read_csv('20260603_지방선거_선거인명부.csv')
df2 = pd.read_csv('20대총선~9회지선_선거인명부.csv')

df3 = pd.concat([df, df1, df2])
df3

,num,sgId,sdName,wiwName,emdName,tpgName,ppltCnt,ntabPpltCnt,frgnrPpltCnt,cfmtnElcnt,...,cfmtnManFrgnrCnt,cfmtnFmlElcnt,cfmtnFmlRacnt,cfmtnFmlFrgnrCnt,cfmtnRdvtDccnt,cfmtnNtabRdvtDccnt,cfmtnRdvtManDccnt,cfmtnNtabRdvtManDccnt,cfmtnRdvtFmlDccnt,cfmtnNtabRdvtFmlDccnt
0,1,20170509,서울특별시,종로구,합계,합계,153672,697,0,133769,...,0,68386,382,0,218,0,184,0,34,0
1,2,20170509,서울특별시,종로구,청운효자동,합계,13588,63,0,11880,...,0,6421,34,0,46,0,42,0,4,0
2,3,20170509,서울특별시,종로구,청운효자동,청운효자동제1투,4399,36,0,4247,...,0,2241,18,0,8,0,7,0,1,0
3,4,20170509,서울특별시,종로구,청운효자동,청운효자동제2투,4670,22,0,3884,...,0,2101,12,0,28,0,27,0,1,0
4,5,20170509,서울특별시,종로구,청운효자동,청운효자동제3투,4519,5,0,3749,...,0,2079,4,0,10,0,8,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105866,96,20160413,제주특별자치도,서귀포시,대천동,대천동제4투,600,0,0,522,...,0,257,0,0,2,0,1,0,1,0
105867,97,20160413,제주특별자치도,서귀포시,대천동,대천동제5투,3021,9,0,2346,...,0,1187,4,0,9,0,8,0,1,0
105868,98,20160413,제주특별자치도,서귀포시,중문동,합계,10019,24,0,8025,...,0,3915,14,0,48,0,38,0,10,0
105869,99,20160413,제주특별자치도,서귀포시,중문동,중문동제1투,5900,12,0,4608,...,0,2271,8,0,26,0,21,0,5,0
105870,100,20160413,제주특별자치도,서귀포시,중문동,중문동제2투,1897,6,0,1544,...,0,741,3,0,15,0,13,0,2,0

In [1]:
import duckdb
import pandas as pd 

df = pd.read_csv('20대총선~9대지선_선거인명부.csv')
df = df.astype({'cfmtnElcnt':'int','ppltCnt':'int'}) 
#cfmtnElcnt: 확정선거인수, ppltCnt:인구수

result = duckdb.query(
    '''
SELECT * 
FROM df 
WHERE tpgName != '합계' 
  AND cfmtnElcnt > ppltCnt;
    '''
).df()[['sgId','sdName','wiwName','emdName','tpgName','ppltCnt','cfmtnElcnt']]

result

         sgId   sdName   wiwName emdName  tpgName  ppltCnt  cfmtnElcnt
0    20170509    서울특별시        중구     소공동   소공동제1투      575        1112
1    20170509    서울특별시       용산구     후암동   후암동제1투     5452        5496
2    20170509    서울특별시      동대문구     용신동   용신동제1투     5214        5246
3    20170509    서울특별시       성북구     성북동   성북동제1투     4938        5065
4    20170509    서울특별시      서대문구     충현동   충현동제1투     4752        4827
..        ...      ...       ...     ...      ...      ...         ...
138  20160413     경상남도  창원시마산합포구     구산면   구산면제1투     1864        2173
139  20160413     경상남도  창원시마산회원구     내서읍   내서읍제1투      609         624
140  20160413     경상남도       밀양시    삼랑진읍  삼랑진읍제1투     3222        3237
141  20160413  제주특별자치도       제주시     한림읍   한림읍제1투     1984        4422
142  20160413  제주특별자치도      서귀포시     대정읍   대정읍제1투     3757        4038

[143 rows x 7 columns]

In [ ]:
df3.to_csv('20대총선~9대지선_선거인명부.csv', index=False)

In [37]:
result.to_excel('인구보다_선거인많은곳(재외국인).xlsx', index=False)

In [2]:
df.to_excel('20대총선~9대지선_선거인명부.xlsx', index=False)

In [27]:
df3['sgId'].unique()

array(['20170509', 20260603, 20250603, 20240410, 20220601, 20220309,
       20200415, 20180613, 20160413], dtype=object)

In [1]:
# 가장 안전하고 확실한 스크래핑 시나리오 예시
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome()
# 1. 일단 정상적인 경로로 페이지에 접속 (세션 및 쿠키 자동 생성됨)
driver.get("https://info.nec.go.kr/main/showDocument.xhtml?electionId=0020250603&topMenuId=VC&secondMenuId=VCAP02&cityCode=1100&townCode=1101&dateCode=1&timeCode=07")

try:
    # 4. [진짜 버튼 클릭] 드디어 대망의 검색 버튼 클릭!
    # 스크린샷에 나온 <input type="image"> 버튼을 정확히 조준해서 클릭 이벤트를 발생시킵니다.
    search_button = driver.find_element(By.CSS_SELECTOR, "#spanSubmit input[type='image']")
    search_button.click()
    
    # 5. 로딩 대기 후 데이터 파싱
    time.sleep(3)
    print("성공적으로 조회를 마쳤습니다!")
    # html = driver.page_source ... 데이터 수집 진행

except Exception as e:
    print("에러 발생:", e)

html_source = driver.page_source
html_source
# 4. 브라우저가 알아서 받아온 화면(HTML)에서 데이터 파싱하기

성공적으로 조회를 마쳤습니다!

'<html lang="ko"><head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n<title>사전투표진행상황(사전투표소별) | 투·개표 | 중앙선거관리위원회 선거통계시스템(최근선거)</title>\n<script type="text/javascript" src="/common/js/jquery/jquery-1.12.1.min.js"></script>\n<link rel="stylesheet" type="text/css" href="/common/css/base_v2.css?ver=231025">\n<link rel="stylesheet" type="text/css" href="/common/css/submains_v2.css?ver=240327">\n<script type="text/javascript" src="/common/js/submains.js?ver=260202"></script><script type="text/javascript" src="/common/js/common.js?ver=240321"></script>\n<script type="text/javascript">\nvar RBtnRemoveList = ["HWP"];\n\t</script>\n<script type="text/javascript" src="/common/js/search.js?ver=231025" charset="utf-8"></script>\n\t<!--[if lt IE 9]>\n\t    <script type="text/javascript" src="/common/js/html5shiv.js"></script>\n\t<![endif]-->\n\t<!--[if lte IE 9]>\n\t\t<link type="text/css" rel="stylesheet" href="/common/css/jquery.Placeholders.monkey.patch.min.css" />\n\t\t<script type="text/javascript" src="/common/js/placeholders.min.js"></script>\n\t\t<script type="text/javascript" src="/common/js/jquery.Placeholders.monkey.patch.min.js"></script>\n\t\t<script type="text/javascript">var underIE = true;</script>\n\t<![endif]-->\n\n</head>\n<body class="bg">\n<div id="skipNav">\n    <a href="#container">본문 바로가기</a>\n</div>\n<div id="wrapper"> \n\t<div class="w_inner"> \n\n\t<div style="display:none;"></div>\n\t\t<div id="header">\n    <div class="top_section">  \n        <h1><a href="/main/main_load.xhtml"><span class="blind">중앙선거관리위원회 선거통계시스템 홈으로 가기</span></a></h1>\n        <ul class="select_election sec">\n\t\t    <li class="eleft"><a href="javascript:void(0)" class="on" title="선택됨"><span>최근선거</span></a></li>\n\t\t    <li class="eright"><a href="/main/main_previous_load.xhtml"><span>역대선거</span></a></li>\n        </ul>\n        <ul class="t_search">\n \t\t\t<li class="tit"><a href="/search/searchCandidate.xhtml">통합검색</a></li>\n \t\t\t<li><input type="text" id="searchKeyword" class="search_input krinput" onkeypress="if(event.keyCode == 13){fn_commonSearch();return false;}" maxlength="30" title="후보자 성명 입력" placeholder="후보자 성명 입력"></li>\n \t\t\t<li><a href="javascript:void(0)" onclick="javascript:fn_commonSearch();" class="btn_t_search searchBtn"><span class="blind">검색</span></a></li>\n\t\t</ul>\n        \n        <div class="s_election" id="s_election">\n            <div class="p_top">\n                <h4>선거선택</h4>\n                <p><a class="cbtn" href="javascript:void(0)"><span>닫기</span></a></p>\n            </div>\n            <div class="p_body">\n               <ul>\n\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020260603&amp;topMenuId=BI">제9회 전국동시지방선거</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI">제21대 대통령선거</a></li>\n\t\t\t\t\t\t</ul>\n            </div>\n        </div>\n        </div>\n    <div id="gnb">\n    \t<h2 class="tit_elect" style="line-height:1.4;">\n\t\t\t<p class="date" style="font-size:17px;">2025년 6월 3일</p>\n\t\t\t<p class="title">제21대 대통령선거</p>\n        </h2>\n        \n        <nav class="gnb_area">\n        \t<ul class="gnblist">\n\t\t\t<li>\n\t\t\t\t\t<a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI" class="m_BI">\n\t\t\t\t\t\t<span>기본현황</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<ul class="sub_menu" style="height: 252px;">\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI&amp;secondMenuId=BIES01">선거일정</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI&amp;secondMenuId=BIGI04">위원회주소</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI&amp;secondMenuId=BIGI05">선거구 및 읍면동현황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI&amp;secondMenuId=BIPB02">선거인명부 확정상황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI&amp;secondMenuId=BIAP01">사전투표소 현황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI&amp;secondMenuId=BIPP01">선거일투표소 현황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=BI&amp;secondMenuId=BICP01">개표소 현황</a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t</li>\t\n\t\t\t<li>\n\t\t\t\t\t<a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=CP" class="m_CP">\n\t\t\t\t\t\t<span>후보자</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<ul class="sub_menu" style="height: 252px;">\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=CP&amp;secondMenuId=CPRI01">후보자 등록수</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=CP&amp;secondMenuId=CPRI03">후보자 명부</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=CP&amp;secondMenuId=CPRI05">사퇴/사망/등록무효</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=CP&amp;secondMenuId=CPRI06">후보자 통계</a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t</li>\t\n\t\t\t<li>\n\t\t\t\t\t<a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC" class="m_VCon">\n\t\t\t\t\t\t<span>투·개표</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<ul class="sub_menu" style="height: 252px;">\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCAP01">사전투표진행상황(위원회별)</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCAP02">사전투표진행상황(사전투표소별)</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCVP01">투표진행상황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCCP09">개표진행상황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCCP08">개표단위별 개표결과</a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t</li>\t\n\t\t\t<li>\n\t\t\t\t\t<a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=EP" class="m_EP">\n\t\t\t\t\t\t<span>당선인</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<ul class="sub_menu" style="height: 252px;">\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=EP&amp;secondMenuId=EPEI01">당선인 명부</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=EP&amp;secondMenuId=EPEI03">당선인 통계</a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t</li>\t\n\t\t\t</ul>\n        </nav>\n\t\t<div class="gnb_bg" style="height: 284px;">\n\t\t</div>\t\t\n        <div class="selSecondMenu">\n        \t<ul class="selSubmu">\n\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCAP01">사전투표진행상황(위원회별)</a></li>\n\t\t\t\t\t\t<li><a class="on" title="선택됨" href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCAP02">사전투표진행상황(사전투표소별)</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCVP01">투표진행상황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCCP09">개표진행상황</a></li>\n\t\t\t\t\t\t<li><a href="/main/showDocument.xhtml?electionId=0020250603&amp;topMenuId=VC&amp;secondMenuId=VCCP08">개표단위별 개표결과</a></li>\n\t\t\t\t\t\t</ul>\n        </div>\n        </div>\n    </div>\n\n\n<div id="pop" style="width: 500px; height: 400px; position: absolute; border: 1px solid rgb(217, 217, 217); background-color: rgb(255, 255, 255); left: 451.5px; top: 90px; display:none" onmousedown="startDrag(event, this)">\n\t<div id="pop_title" class="title"><h3 align="center" style="margin: 0; padding: 10px; background-color:#2e3d64; color: #fff;">공지사항</h3></div>\n\t<div id="pop_main" style="padding: 20px;">\n\t\t<p style="font-size:25px;">선거통계시스템 작업 안내<br><br></p>\n\t\t<p style="font-size:18px;">선거통계시스템의 안정적 서비스를 위한 서버점검 작업으로 <br>일부서비스가 원활하지 않을 수 있음을 알려드립니다.<br><br></p>\n\t\t<p style="font-size:16px;">☞ 작업일시<br>2023. 9. 26.(화) 18:00 ~ 9. 27.(수) 09:00<br></p>\n\t</div>\n\t<div id="pop_close" style="position:absolute; left:0; right: 0; bottom: 0; padding: 10px; background-color:#555; color: #fff;">\n\t\t<div style="text-align:left">\n\t\t\t<input type="checkbox" id="todayClose" class="todayClose">\n \t\t\t<label for="todayClose">오늘하루 그만보기</label>\n\t\t\t<input style="font-size: 13px; background-color: #555; color: white; padding-top: 2px; float:right;" type="button" id="buttonClose" class="buttonClose" value="창닫기" onclick="javascript:checkedFunc();">\n\t\t</div>\n\t</div>\n   </div>\n\n<script type="text/javascript">\n\n$(function(){\n\t\n\tvar electionId = "0020250603";    \n\t\n    \n\tvar secondMenuId = "VCAP02";\n\t\n    \n\tvar menuId = [];\n\t\n    \n    if(menuId.length > 0){\n    \tfor(var i=0; i <= menuId.length; i++){\n    \t\tif(menuId[i] == secondMenuId){\n    \t\t\tif (getCookie("subNoticePop") != "done") {\n    \t\t\t\t\n    \t\t\t\tpopupOpen();\n    \t\t\t}\n    \t\t}\n    \t}\n    }\n});\n\n\n\nfunction popupOpen() {\n\tvar width = $(window).width();\n\tvar height = $(window).height();\n\t\n\t$(\'#pop\').css("z-index", "9999");\n\t$(\'#pop\').css("position", "absolute");\n\t$(\'#pop\').css("border", "1px solid #d9d9d9");\n\t$(\'#pop\').css("background-color", "#fff");\n\t$(\'#pop\').css({\'left\':(width - 500 )/2, \'top\':(height - 500 )/2 });\n\t$(\'#pop\').show();\n}\n\n\nvar img_L = 0;\nvar img_T = 0;\nvar targetObj;\n\nfunction getLeft(o) {\n\treturn parseInt(o.style.left.replace(\'px\', \'\'));\n}\n\nfunction getTop(o) {\n\treturn parseInt(o.style.top.replace(\'px\', \'\'));\n}\n\nfunction moveDrag(e) {\n\tvar e_obj = window.event? window.event : e;\n\tvar dmvx = parseInt(e_obj.clientX + img_L);\n\tvar dmvy = parseInt(e_obj.clientY + img_T);\n\t\n\ttargetObj.style.left = dmvx+"px";\n\ttargetObj.style.top = dmvy+"px";\n\treturn false;\n}\n\nfunction startDrag(e, obj){\n\ttargetObj = obj;\n\tvar e_obj = window.event? window.event : e;\n\t\n\timg_L = getLeft(obj) - e_obj.clientX;\n\timg_T = getTop(obj) - e_obj.clientY;\n\t\n\tdocument.onmousemove = moveDrag;\n\tdocument.onmouseup = stopDrag;\n\tif(e_obj.preventDefault)e_obj.preventDefault();\n}\n\nfunction stopDrag() {\n\tdocument.onmousemove = null;\n\tdocument.onmouseup = null;\n}\n\n\t\nfunction getCookie(name) {\n\tvar nameOfCookie = name + "=";\n\tvar x = 0;\n\twhile (x <= document.cookie.length) {\n\t\tvar y = (x + nameOfCookie.length);\n\t\tif (document.cookie.substring(x, y) == nameOfCookie) {\n\t\t\tif ((endOfCookie = document.cookie.indexOf(";", y)) == -1)\n\t\t\t\tendOfCookie = document.cookie.length;\n\t\t\treturn unescape(document.cookie.substring(y, endOfCookie));\n\t\t}\n\t\tx = document.cookie.indexOf(" ", x) + 1;\n\t\tif (x == 0)\n\t\t\tbreak;\n\t}\n\treturn "";\n}\n\nfunction setCookie(name, value, expiredays) {\n\tvar todayDate = new Date();\n\ttodayDate.setDate(todayDate.getDate() + expiredays);\n\tdocument.cookie = name + "=" + escape(value) + "; path=/; expires="\t+ todayDate.toGMTString() + ";";\n}\n\n\nvar checkedFunc = function() {\n\tvar todayCheck = document.getElementById(\'todayClose\');\n\tif (todayCheck.checked) {\n\t\tsetCookie("subNoticePop", "done", 1);\n\t\t$(\'#pop\').hide();\n\t} else {\n\t\t$(\'#pop\').hide();\n\t}\n};\n\n</script><style type="text/css" media="all" title="default">@import "/common/css/base_v2.css?ver=231025";</style>\n\n<script type="text/javascript" charset="utf-8" src="/common/js/jquery/jquery-1.12.1.min.js"></script>\n<script type="text/javascript" charset="utf-8" src="/common/js/jquery/jquery.blockUI.js"></script>\n<script type="text/javascript" charset="utf-8" src="/common/js/jquery/jquery.jsonUtil.js"></script>\n<script type="text/javascript" charset="utf-8" src="/common/js/electioncommon.js?ver=260326"></script>\n<script type="text/javascript" charset="utf-8" src="/ubi4/js/ubi.js?ver=240201"></script>\n<script type="text/javascript">\n$(document).ready(function() {\n\tif($("#electionType0").hasClass("on")){\n\t\t$("select#electionName").attr("title", "선거일자");\n\t}\n\telse{\n\t\t$("select#electionName").attr("title", "선거회차");\t\n\t}\n\t$("select#electionNameJaeBo").attr("title", "선거일자");\n\t$("select#electionCode").attr("title", "선거구분");\n\t$("select#cityCode").attr("title", "시도");\n\t$("select#sggCityCode").attr("title", "선거구");\n\t$("select#townCode").attr("title", "구시군");\n\t$("select#townCodeFromSgg").attr("title", "구시군");\n\t$("select#sggTownCode").attr("title", "선거구(구시군)");\n\t$("select#proportionalRepresentationCode").attr("title", "비례정당");\n\t$("select#genderCode").attr("title", "성별");\n\t$("select#dateCode").attr("title", "투표일자");\n\t$("select#searchType").attr("title", "조회구분");\n\t$("select#registorPartyCode").attr("title", "조회구분");\n\t$("select#giguCode").attr("title", "선거운동기구");\n\t$("select#maxMinCode").attr("title", "최다최소");\n\t$("select#timeCode").attr("title", "투표시간");\n\t\n});\n</script><script type="text/javascript">\n//<[CDATA[\nvar DOC = {ROOT : \'\'};\nvar previousCityCode = \'1100\';\nvar previousTownCode = \'1101\';\n\n\n\tvar RBtnRemoveList = ["HWP"];\n\n\n\n$(document).ready(function(){\n\t$(\'#searchForm\').submit(chooseStatementId);\n\t$(\'#cityCode\').change(changeCityCode);\n\t$(\'#dateCode\').change(changeDateCode);\n\tsetSubTitle();\n\tsettingYN();\n});\n\t\n\nfunction setSubTitle() {\n\tif ($(\'#cityCode\').val() > 0) {\n\t\t$(\'#cityName\').html(retrieveSelectedName(\'cityCode\'));\n\t}\n\tif ($(\'#townCode\').val() > 0) {\n\t\t$(\'#townName\').html(retrieveSelectedName(\'townCode\'));\n\t}\n\tif ($(\'#dateCode\').val() > 0) {\n\t\t$(\'#dateName\').html(retrieveSelectedName(\'dateCode\'));\n\t}\n\tif ($(\'#timeCode\').val() > 0) {\n\t\t$(\'#timeName\').html(retrieveSelectedName(\'timeCode\'));\n\t}\n}\n\t\n\nfunction changeCityCode(e){\n\t$(\'#townCode\').val(0);\n\t$(\'#dateCode\').val(0);\n\t$(\'#timeCode\').val(0);\n\tsettingYN();\n}\n\t\n\nfunction changeDateCode(e){\t\t\n\tif($(\'#dateCode\').val() == 3){ \n\t\t$(\'#timeCode\').val("07");\t\n\t}else{\n\t\t$(\'#timeCode\').val(0);\n\t}\n\tsettingYN();\n}\n\t\n\nfunction settingYN(e) {\n\tvar electionId = $(\'#electionId\').val();\n\tvar cityCode = $(\'#cityCode\').val();\n\tvar townCode = $(\'#townCode\').val();\n\tvar dateCode = $(\'#dateCode\').val();\n\t\t\n\tif( cityCode == 0 ){\n\t\t\n\t\tif( dateCode == 0 ){\n\t\t\tselectBoxShow(\'none\');\n\t\t\tif($("#timeCode [value=\'0\']").length == 0){\n\t\t\t\t$("#timeCode").prepend(\'<option value="0">▷ 전체</option>\');\n\t\t\t}\n\t\t}else{\n\t\t\t\n\t\t\tif(dateCode == 3){\n\t\t\t\t\n\t\t\t\t$("#timeCode [value=\'0\']").remove();\n\t\t\t\tselectBoxShow(\'\');\n\t\t\t\n\t\t\t\n\t\t\t}else{\n\t\t\t\tif($("#timeCode [value=\'0\']").length == 0){\n\t\t\t\t\t\n\t\t\t\t\t$("#timeCode").prepend(\'<option value="0">▷ 전체</option>\');\n\t\t\t\t}\n\t\t\t\tselectBoxShow(\'\', \'\');\n\t\t\t}\n\t\t}\n\t}else if( cityCode > 0 ){\n\t\tselectBoxShow(\'none\');\n\t\tcheckPreviousCityCode(cityCode);\n\t\t\t\n\t\t\n\t\tif( dateCode == 0 ){\n\t\t\tselectBoxShow(\'none\');\n\t\t\tif($("#timeCode [value=\'0\']").length == 0){\n\t\t\t\t$("#timeCode").prepend(\'<option value="0">▷ 전체</option>\');\n\t\t\t}\n\t\t}else{\n\t\t\t\n\t\t\tif(dateCode == 3){\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t\t$("#timeCode [value=\'0\']").remove();\n\t\t\t\tselectBoxShow(\'\');\n\t\t\t\t\n\t\t\t\n\t\t\t}else{\n\t\t\t\tif($("#timeCode [value=\'0\']").length == 0){\n\t\t\t\t\t\n\t\t\t\t\t$("#timeCode").prepend(\'<option value="0">▷ 전체</option>\');\n\t\t\t\t}\n\t\t\t\tselectBoxShow(\'\');\n\t\t\t}\n\t\t}\n\t\tif (townCode == \'\' || townCode == null) {\n\t\t\t$(\'#townCode\').val(0);\n\t\t}\n\t}\n}\n\n\nfunction checkPreviousCityCode(cityCode){\n\tif(previousCityCode != cityCode){\n\t\tcreateTownCodes();\n\t\tpreviousCityCode = cityCode;\t\n\t}\n}\n\n\nfunction selectBoxShow(timeSpanStyle) {\n\t$(\'#spanTimeCode\').css(\'display\',timeSpanStyle);\n}\n\t\n\nfunction createTownCodes(e) {\n\tvar locationStr = DOC.ROOT+\'/bizcommon/selectbox/selectbox_townCodeJson.json\';\n\tvar electionId = $(\'#electionId\').val();\n\tvar cityCode = $(\'#cityCode\').val();\n\n\tvar params ={\n\t\t\tcityCode : cityCode,\n\t\t\telectionId : electionId\n\t\t};\n\n\t$(\'#cityCode\').attr(\'disabled\', true);\n\t$.getJSONTE(locationStr, params,\n\t\tfunction(response, status){\n\t\t\tvar searchType = $(\'#searchType\').val();\n\t\t\tvar electionCode = $(\'#electionCode\').val();\n\n\t\t\tvar townCodeList = response;\n\n\t\t\tvar townCodeEl = $(\'#townCode\');\n\t\t\t//선택과 전체 옵션을 제외한 나머지 옵션을 제거\n\t\t\t$(\'#townCode option\').filter(function(){\n\t\t\t\t$value = $(this).val();\n\t\t\t\tif($value != -1 && $value != 0){return this;}\n\t\t\t}).remove();\n\n\t\t\t//townCode 옵션 추가\n\t\t\tfor(var i = 0; i<townCodeList.length; i++){\n\t\t\t\tvar option = $(\'<option>\').attr(\'value\', townCodeList[i].CODE).html(townCodeList[i].NAME);\n\t\t\t\toption.appendTo(townCodeEl);\n\t\t\t}\n\n\t\t\t//검색 이후 구시군 코드를 호출시에 이전 선택한 값을 선택상태로 변경\n\t\t\tif(previousTownCode) {\n\t\t\t\tsetTimeout(function(){\n\t\t\t\t\t$(\'#townCode\').val(previousTownCode);\n\t\t\t\t\tsettingYN();\n\t\t\t\t}, 50);\n\t\t\t}\n\t\t\tchooseStatementId();\n\t\t},\n\t\tfunction(response, status){\n\t\t\t$(\'#cityCode\').attr(\'disabled\', false);\n\t\t}\n\t);\n}\n\n\nfunction chooseStatementId() {\n\tvar cityCode = $(\'#cityCode\').val();\n\tvar townCode = $(\'#townCode\').val();\n\tvar statementId = "";\n\t\t\n\tif(cityCode == 0){\n\t\tstatementId = "VCAP02_#1";\n\t}else if(cityCode > 0){\n\t\tif(townCode == 0){\n\t\t\tstatementId = "VCAP02_#2";\n\t\t}else{\n\t\t\tstatementId = "VCAP02_#3";\n\t\t}\n\t}\n\t$(\'#statementId\').val(statementId);\n}\n//]]>\n</script>\n\n\n<div id="container">\n\t<div id="container_inner" class="clearfix">\n\n\t    <div id="contentarea">\n          \n\t\t\t<div class="titlearea">\n            \t<h3 class="t_VC">투·개표</h3>\n\t\t\t\t<div class="r_title">\n\t\t\t\t \t<h4>사전투표진행상황(사전투표소별)</h4>\n\t\t\t\t \t<ul class="location">\n\t\t\t\t\t\t<li class="home"><i class="blind">홈</i></li>\n\t\t\t\t\t\t<li>제21대 대통령선거</li>\n\t\t\t\t\t\t<li>투·개표</li>\n\t\t\t\t\t\t<li>사전투표진행상황(사전투표소별)</li>\n\t\t\t\t\t</ul>\n            \t</div>\n           \t</div>\n           \t<div class="bodyarea">\n\t\t\t\t<div class="filter">\n\t\t\t\t \t<form id="searchForm" action="/electioninfo/electionInfo_report.xhtml" method="post">\n\t\t\t\t \t\t<input type="hidden" id="electionId" name="electionId" value="0020250603">\n<input type="hidden" id="requestURI" name="requestURI" value="/electioninfo/0020250603/vc/vcap02.jsp">\n<input type="hidden" id="topMenuId" name="topMenuId" value="VC">\n<input type="hidden" id="secondMenuId" name="secondMenuId" value="VCAP02">\n<input type="hidden" id="menuId" name="menuId" value="VCAP02">\n<input type="hidden" id="statementId" name="statementId" value="0020250603.VCAP02_#3">\n\t\t\t\t\t\t<input type="hidden" id="prevoteDate1" name="prevoteDate1" value="20250529">\n\t\t\t\t\t\t<input type="hidden" id="prevoteDate2" name="prevoteDate2" value="20250530">\n\t\t\t\t\t\t\n\t\t\t\t\t\t<div class="f_select">\n\t\t                \t<dl>\n\t\t\t\t\t\t\t\t<dt>조회조건</dt>\n\t\t\t\t\t\t\t\t<dd>\t\n\t\t\t\t\t\t\t\t\t<span id="wub_select">\n\t\t\t\t\t\t\t      \t\t<div class="wub_select1">\n\t\t\t\t\t\t\t\t\t\t\t<span id="spanCityCode">\n\t\t\t\t\t\t\t\t\t\t\t\t<label id="cityCodeLabel" class="label" for="cityCode">시도</label>\n\t\t\t\t\t\t\t\t\t\t\t\t<select id="cityCode" name="cityCode" title="시도">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- option value="-1">▽ 선 택</option -->\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option value="0">▷ 전 체</option>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option value="1100" selected="selected">서울특별시</option>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option value="2600">부산광역시</option>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option value="2700">대구광역시</option>\n\t\t\t\t\t\t\t\

In [9]:
from bs4 import BeautifulSoup

html = BeautifulSoup(html_source, 'html.parser')
table = html.select("#table01")

headers = [th.text.strip() for th in table[0].find('thead').find_all('th')]

# 2. 바디(데이터행) 추출하기
rows = table[0].find('tbody').find_all('tr')

data_list = []
for row in rows:
    # 행 안의 td(셀)들을 다 찾아서 텍스트만 리스트로 만듭니다.
    cells = row.find_all('td')
    row_data = [cell.text.strip() for cell in cells]
    data_list.append(row_data)

import pandas as pd

df = pd.DataFrame(data_list, columns=headers)
df

           읍면동명            사전투표소명 사전투표자수 관내사전투표자수 관외사전투표자수
0            합계                    2,477    1,412    1,065
1         청운효자동        청운효자동사전투표소    167      129       38
2           사직동          사직동사전투표소    179       63      116
3           삼청동          삼청동사전투표소     47       17       30
4           부암동          부암동사전투표소     86       58       28
5           평창동          평창동사전투표소    161      120       41
6           무악동          무악동사전투표소    123       90       33
7           교남동          교남동사전투표소    173       99       74
8           가회동          가회동사전투표소    150       53       97
9   종로1·2·3·4가동  종로1·2·3·4가동사전투표소    200       91      109
10      종로5·6가동      종로5·6가동사전투표소    202       56      146
11          이화동          이화동사전투표소    121       71       50
12          혜화동          혜화동사전투표소    241      151       90
13        창신제1동        창신제1동사전투표소    169      100       69
14        창신제2동        창신제2동사전투표소    108       89       19
15        창신제3동        창신제3동사전투표소     96       58       38
16        숭인제1동        숭인제1동사전투표소     93       69       24
17        숭인제2동        숭인제2동사전투표소    161       98       63

In [ ]:
import pandas as pd 

sheet_id = "1sBLCs8So45lCD5xQfhmrPr_HlA1zgwR0-i1T23bw09s"
gid = "2022903059" # 관내: 2022903059, 관외: 1608939986
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

df = pd.read_csv(url)
df

,ID,구시군명,읍면동명,사전투표소명,1일차 7시,8시,9시,10시,11시,12시,13시,14시,15시,16시,17시,18시,투표율
0,1,종로구,청운효자동,청운효자동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,종로구,사직동,사직동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,종로구,삼청동,삼청동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,종로구,부암동,부암동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,종로구,평창동,평창동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,종로구,무악동,무악동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,종로구,교남동,교남동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,종로구,가회동,가회동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,종로구,종로1·2·3·4가동,종로1·2·3·4가동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,종로구,종로5·6가동,종로5·6가동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,종로구,이화동,이화동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,종로구,혜화동,혜화동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,종로구,창신제1동,창신제1동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,종로구,창신제2동,창신제2동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,종로구,창신제3동,창신제3동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,종로구,숭인제1동,숭인제1동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,종로구,숭인제2동,숭인제2동사전투표소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN